---
# Source: networkconnectivity-test-controller/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: networkconnectivity-test-controller
  namespace: default
  labels:
    app.kubernetes.io/name: networkconnectivity-test-controller
    helm.sh/chart: networkconnectivity-test-controller
    app.kubernetes.io/instance: release-name

---
# Source: networkconnectivity-test-controller/templates/rbac.yaml
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: networkconnectivity-test-controller
  labels:
    app.kubernetes.io/name: networkconnectivity-test-controller
    helm.sh/chart: networkconnectivity-test-controller
    app.kubernetes.io/instance: release-name
rules:
  - apiGroups:
      - networkmachinery.io
    resources:
      - networkconnectivitytest
      - networkconnectivitytests
      - networkmonitor
      - networkmonitors
      - networknotification
      - networknotifications
      - networktrafficshaper
      - networktrafficshapers
      - networkconnectivitytest/status
      - networkconnectivitytests/status
    verbs:
      - get
      - list
      - watch
      - patch
      - update
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/log
      - services
      - endpoints
    verbs:
      - get
      - list
      - watch
      - create
  - apiGroups:
      - ""
    resources:
      - pods/exec
    verbs:
      - create
  - apiGroups:
      - authorization.k8s.io
    resources:
      - selfsubjectaccessreviews
    verbs:
      - create
      - list
      - get
  - apiGroups:
      - ""
    resources:
      - configmaps
    resourceNames:
      - networkconnectivity-test-controller-leader-election
      - sflow-controller-leader-election
      - network-control-controller-leader-election
      - network-traffic-shaper-leader-election
    verbs:
      - get
      - watch
      - update
      - patch
  - apiGroups:
      - ""
      - batch
      - rbac.authorization.k8s.io
      - admissionregistration.k8s.io
    resources:
      - events
      - secrets
      - configmaps
      - services
      - serviceaccounts
      - roles
      - rolebindings
      - mutatingwebhookconfigurations
      - validatingwebhookconfigurations
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: networkconnectivity-test-controller
  labels:
    app.kubernetes.io/name: networkconnectivity-test-controller
    helm.sh/chart: networkconnectivity-test-controller
    app.kubernetes.io/instance: release-name
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: networkconnectivity-test-controller
subjects:
  - kind: ServiceAccount
    name: networkconnectivity-test-controller
    namespace: default

---
# Source: networkconnectivity-test-controller/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: networkconnectivity-test-controller
  namespace: default
  labels:
    app.kubernetes.io/name: networkconnectivity-test-controller
    helm.sh/chart: networkconnectivity-test-controller
    app.kubernetes.io/instance: release-name
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: networkconnectivity-test-controller
      app.kubernetes.io/instance: release-name
  template:
    metadata:
      labels:
        app.kubernetes.io/name: networkconnectivity-test-controller
        app.kubernetes.io/instance: release-name
    spec:
      serviceAccountName: networkconnectivity-test-controller
      containers:
        - name: networkconnectivity-test-controller
          image: "zanetworker/networkmachinery-hyper:latest"
          imagePullPolicy: Always
          command:
            - /opt/networkmachinery-operators/bin/networkmachinery-hyper
            - networkconnectivity-test-controller
          ports:
            - name: webhook-server
              containerPort: 9876
              protocol: TCP
          volumeMounts:
            - name: cert
              mountPath: /tmp/k8s-webhook-server/serving-certs #default path
      volumes:
        - name: cert
          secret:
            secretName: networkconnectivity-layer-validator-secret
            defaultMode: 420
---
apiVersion: v1
kind: Secret
metadata:
  name: networkconnectivity-layer-validator-secret
  namespace: default

